### ISSUE TITLE
Feature: Mock-up

### ISSUE THREAD

**Issue by FedeBayer** [FedeBayer/portfolio-FrontEnd#2]
This feature will add a static mock-up of the portfolio.
1. [x] [Task 1: Initial layout of the mock-up](https://github.com/FedeBayer/portfolio-FrontEnd/issues/3)
2. [x] [Task 2: Assign personal information in the mock-up](https://github.com/FedeBayer/portfolio-FrontEnd/issues/4)
3. [x] [Task 3: Add a description of the mock-up in the wiki](https://github.com/FedeBayer/portfolio-FrontEnd/issues/1)
