### ISSUE TITLE
Feature: Angular redesign

### ISSUE THREAD

**Issue by FedeBayer** [FedeBayer/portfolio-FrontEnd#8]
This feature will redesign the mock-up of the portfolio using Angular to make an SPA.
1. [x] [Task 1: Create an SPA with Angular](https://github.com/FedeBayer/portfolio-FrontEnd/issues/9)
2. [x] [Task 2: Use Modulation](https://github.com/FedeBayer/portfolio-FrontEnd/issues/10)
3. [x] [Task 3: Add a description of the Angular redesign in the wiki](https://github.com/FedeBayer/portfolio-FrontEnd/issues/11)
